### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kirantpatil** [kambrium/staticmapservice#3]
I used below URL to generate the staticmap and it resulted in "500 Internal Server Error"

http://127.0.0.1:5000/?w=400&h=300&z=9&marker=coords:48.25,11.22|diam:10|color:%233F33FF

Error in Browser
----
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Application terminal log messages:
---

> $ flask run
>  * Serving Flask app "staticmapservice.py"
>  * Environment: production
>    WARNING: Do not use the development server in a production environment.
>    Use a production WSGI server instead.
>  * Debug mode: off
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> 127.0.0.1 - - [23/Sep/2019 10:33:54] "GET / HTTP/1.1" 400 -
> 127.0.0.1 - - [23/Sep/2019 10:33:54] "GET /robots.txt HTTP/1.1" 404 -
> 127.0.0.1 - - [23/Sep/2019 10:33:54] "GET /favicon.ico HTTP/1.1" 404 -
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> [2019-09-23 10:34:17,006] ERROR in app: Exception on / [GET]
> Traceback (most recent call last):
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/staticmapservice.py", line 102, in create_map
>     image = static_map.render(zoom=zoom, center=center)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/staticmap/staticmap.py", line 285, in render
>     self._draw_base_layer(image)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/staticmap/staticmap.py", line 412, in _draw_base_layer
>     raise RuntimeError("could not download {} tiles: {}".format(len(tiles), tiles))
> RuntimeError: could not download 6 tiles: [(271, 176, 'http://a.tile.osm.org/9/271/176.png'), (271, 177, 'http://a.tile.osm.org/9/271/177.png'), (271, 178, 'http://a.tile.osm.org/9/271/178.png'), (272, 176, 'http://a.tile.osm.org/9/272/176.png'), (272, 177, 'http://a.tile.osm.org/9/272/177.png'), (272, 178, 'http://a.tile.osm.org/9/272/178.png')]
> 127.0.0.1 - - [23/Sep/2019 10:34:17] "GET /?w=400&h=300&z=9&marker=coords:48.25,11.22|diam:10|color:%233F33FF HTTP/1.1" 500 -
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> [2019-09-23 10:34:28,339] ERROR in app: Exception on / [GET]
> Traceback (most recent call last):
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/staticmapservice.py", line 102, in create_map
>     image = static_map.render(zoom=zoom, center=center)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/staticmap/staticmap.py", line 285, in render
>     self._draw_base_layer(image)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/staticmap/staticmap.py", line 412, in _draw_base_layer
>     raise RuntimeError("could not download {} tiles: {}".format(len(tiles), tiles))
> RuntimeError: could not download 6 tiles: [(271, 176, 'http://a.tile.osm.org/9/271/176.png'), (271, 177, 'http://a.tile.osm.org/9/271/177.png'), (271, 178, 'http://a.tile.osm.org/9/271/178.png'), (272, 176, 'http://a.tile.osm.org/9/272/176.png'), (272, 177, 'http://a.tile.osm.org/9/272/177.png'), (272, 178, 'http://a.tile.osm.org/9/272/178.png')]
> 127.0.0.1 - - [23/Sep/2019 10:34:28] "GET /?w=400&h=300&z=9&marker=coords:48.25,11.22|diam:10|color:%233F33FF HTTP/1.1" 500 -
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> request failed [?]: http://a.tile.osm.org/9/271/176.png
> request failed [?]: http://a.tile.osm.org/9/271/177.png
> request failed [?]: http://a.tile.osm.org/9/271/178.png
> request failed [?]: http://a.tile.osm.org/9/272/176.png
> request failed [?]: http://a.tile.osm.org/9/272/177.png
> request failed [?]: http://a.tile.osm.org/9/272/178.png
> [2019-09-23 10:34:42,252] ERROR in app: Exception on / [GET]
> Traceback (most recent call last):
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/staticmapservice.py", line 102, in create_map
>     image = static_map.render(zoom=zoom, center=center)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/staticmap/staticmap.py", line 285, in render
>     self._draw_base_layer(image)
>   File "/home/smitha/Documents/Fueb/Rtt/staticmapservice/lib/python3.6/site-packages/staticmap/staticmap.py", line 412, in _draw_base_layer
>     raise RuntimeError("could not download {} tiles: {}".format(len(tiles), tiles))
> RuntimeError: could not download 6 tiles: [(271, 176, 'http://a.tile.osm.org/9/271/176.png'), (271, 177, 'http://a.tile.osm.org/9/271/177.png'), (271, 178, 'http://a.tile.osm.org/9/271/178.png'), (272, 176, 'http://a.tile.osm.org/9/272/176.png'), (272, 177, 'http://a.tile.osm.org/9/272/177.png'), (272, 178, 'http://a.tile.osm.org/9/272/178.png')]
> 127.0.0.1 - - [23/Sep/2019 10:34:42] "GET /?w=400&h=300&z=9&marker=coords:48.25,11.22|diam:10|color:%233F33FF HTTP/1.1" 500 -
>

**Comment by kambrium** [comment]
I assume that this has something to do with the library staticmap. Will open an issue...

**Comment by kambrium** [comment]
Possibly komoot abandoned the development of staticmap. There are no commits this year and they don‘t respond to my issue. If I have time during the next days I will have a look at their code in order to solve this problem.

**Comment by kirantpatil** [comment]
Great, I appreciate your effort.

Thanks a lot for your support.

**Comment by kirantpatil** [comment]
Dear Sir,

Any updates on this issue ?

**Comment by kambrium** [comment]
I might have time to deal with that issue at the end of this week...

**Comment by kambrium** [comment]
It seems that missing headers are the reason for this issue. See the solution by @brauchle: https://github.com/komoot/staticmap/issues/19#issuecomment-544160392. I think I will have to add a possibility to set a header.

**Comment by kambrium** [comment]
Just pushed the fix. Hope that everything works as you expect.
